### ISSUE TITLE
Add Negative YouTube Embed Margin

### ISSUE THREAD

**Issue by RehanSaeed** [RehanSaeed/rehansaeed.github.io#29]
https://github.com/noxify/gridsome-plugin-remark-embed/issues/35

**Comment by RehanSaeed** [comment]
Currently using:

```
div[style="width: 100%; margin: 25px 0 25px 0;"] div {
    margin-left: var(--global-space-fluid--6);
    margin-right: var(--global-space-fluid--6);
}
```

**Comment by noxify** [comment]
Hi @RehanSaeed 

i think i will remove the option to define a margin, because I added some wrapper classes around the embeds. 

So you can control it via CSS by your own.
